Update common.go
Win11 reporting:
ERROR: 2025/08/26 09:38:55 Failed to configure interface: netsh command failed: exec: "netsh": cannot run executable found relative to current directory, output:
--
Ref: 
indicates a security measure implemented in Go 1.19 and later versions, affecting how executables are resolved via the system's PATH environment variable. Specifically, the os/exec package in Go will no longer resolve a program using an implicit or explicit path entry relative to the current directory (e.g., ./go on Unix or .\go.exe on Windows), even if the PATH is configured to allow it.